### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by mabushey** [valentincanonical/coloriser-demo#4]
docker logs colouriser-demo-frontend-1
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/sites-available/default.conf
ln: failed to create symbolic link '/etc/nginx/sites-enabled/default.conf': File exists
```

The frontend container keeps restarting after a `docker-compose up -d`

**Comment by valentincanonical** [comment]
Thanks @mabushey for reaching out!

This is probably because you already deployed it once before and stopped it with a SIGTERM instead of a `docker-compose down` command? Then the containers are not always recreated and the file changes remain between restarts, thus causing NGINX entrypoint to fail (as it expects a pristine container image).

Workarounds are: 

1/ stop the deployment with `docker-compose down` between restarts, or,
2/ append `--force-recreate` to your `up` command, such as, `docker-compose up -d --force-recreate`

Feel free to suggest another solution if you can think of anything that would be more transparent to the user. I'm closing the issue as the workarounds should hopefully make it work; feel free to reopen otherwise!

**Comment by mabushey** [comment]
Thanks for the help.
