### ISSUE TITLE
Error getting version v1, v2

### ISSUE THREAD

**Issue by mabushey** [valentincanonical/coloriser-demo#5]
Now I get the Web Interface after running `docker-compose up -d --force-recreate`. :)
```
docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS          PORTS                            NAMES
17c51c9b7067   colouriser-demo-backend       "/opt/venv/bin/pytho…"   11 minutes ago   Up 11 minutes   0.0.0.0:8080->5000/tcp           colouriser-demo-backend-1
dddbbeae16ba   colouriser-demo-modelserver   "/ovms/bin/ovms --co…"   11 minutes ago   Up 11 minutes   0.0.0.0:9001->9001/tcp           colouriser-demo-modelserver-1
d580f90f0e99   colouriser-demo-frontend      "/docker-entrypoint.…"   11 minutes ago   Up 11 minutes   80/tcp, 0.0.0.0:8000->3000/tcp   colouriser-demo-frontend-1
```

When I upload an image to `http://127.0.0.1:8000`, I see the B&W photo under `Original`, but `Colourised V1` has `Error getting version v1` and `Colourised V2` has `Error getting version v2`. I'm running Arch, 128GB Ram and 24GB Nvidia RAM.

**Comment by valentincanonical** [comment]
Hey @mabushey , thanks for opening the bug! (This repo was meant as a quick PoC for the blog series: https://ubuntu.com/blog/how-to-colourise-black-white-pictures-openvino-containers-part-1 and https://www.docker.com/blog/how-to-colorize-black-white-pictures-ubuntu-containers/. Therefore I'm expecting a lot of small bad surprises like this one ;) )

I do believe this was caused by a 413 "payload too large" error on the reverse proxy end. But without more information this is hard to confirm. 

Please try again with the latest version available on the main branch. If the issue persists, could you please reopen this issue with a copy and paste of the logs from your browser web console?

**Comment by mabushey** [comment]
`client_max_body_size 20M;` did it! Thanks!
